FROM python:3.10-slim

WORKDIR /app
COPY basestationproject/fastapi_server/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY basestationproject/fastapi_server/main.py ./

EXPOSE 8080
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
