# Dockerfile.fastapi
FROM ros:humble-ros-core-jammy

RUN apt-get update && \
    apt-get install -y python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    pip install fastapi

WORKDIR /app
COPY basestationproject/fastapi_server/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY basestationproject/fastapi_server/main.py ./

ENTRYPOINT ["/bin/bash","-c", \
  "source /opt/ros/humble/setup.sh && \
   source /ros2_ws/install/setup.sh && \
   exec uvicorn main:app --host 0.0.0.0 --port 8080 --reload"]
EXPOSE 8080
