services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile.ros2_base
    container_name: ros2_base
    networks:
      - basestation_net
    volumes:
      - ros2_build:/ros2_ws
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]




  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: basestation_django
    depends_on:
      - ros2
      - redis
    networks:
      - basestation_net
    environment:
      DJANGO_SETTINGS_MODULE: basestationproject.settings
      REDIS_URL: redis://redis:6379/0
    volumes:
      - django_static:/app/static
      - django_media:/app/media
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine
    container_name: basestation_redis
    networks:
      - basestation_net
    ports:
      - "6379:6379"

  fastapi_drivetrain:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: basestation_fastapi_drivetrain
    depends_on:
      - ros2
    networks:
      - basestation_net
    ports:
      - "8080:8080"

  fastapi_process:
    build:
      context: .
      dockerfile: Dockerfile.process
    container_name: basestation_fastapi_process
    depends_on:
      - ros2
      - redis
    networks:
      - basestation_net
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: basestation_frontend
    depends_on:
      - django
      - fastapi_drivetrain
    networks:
      - basestation_net
    ports:
      - "3000:3000"

volumes:
  ros2_build:
  django_static:
  django_media:

networks:
  basestation_net:
    driver: bridge
