"""
Django settings for basestationproject project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&1pq07r=(c=h%t+_5v%f^$@99l3tfc77r*=nlv#&%%_*iw(#$w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow server IP (10.0.0.1) and client IP (10.0.0.2) when binding to eth interface
ALLOWED_HOSTS = ['*', '10.0.0.1', '10.0.0.2']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_redis',
    'corsheaders',
    'rest_framework',
    'backendapi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'backendapi.pin_middleware.PinAuthMiddleware',
    'backendapi.request_logging_middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'basestationproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'basestationproject.wsgi.application'


CSRF_TRUSTED_ORIGINS = [
  'http://localhost:3000',
  "http://127.0.0.1:3000",
  'http://localhost:8000',
  'http://localhost:8080',
  'http://127.0.0.1:8080',
  'http://django_server:8000',
  # Access from client at 10.0.0.2 to server at 10.0.0.1
  'http://10.0.0.1',
  'http://10.0.0.1:8000',
  'http://10.0.0.1:8080',
  'http://10.0.0.2',
  'http://10.0.0.2:3000',
  'http://10.0.0.2:8080',
  'http://localhost:5173',
  'http://127.0.0.1:5173',
  'http://10.42.0.11',
  'http://10.42.0.11:3000',
  'http://10.42.0.11:8080',
  'http://10.42.0.11:5173',
]

# When credentials are included, Access-Control-Allow-Origin cannot be '*'.
# Use explicit origins instead of CORS_ALLOW_ALL_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://django_server:8000",
    "http://10.0.0.1",
    "http://10.0.0.1:8000",
    "http://10.0.0.1:8080",
    "http://10.0.0.1:5173",
    "http://10.0.0.2",
    "http://10.0.0.2:3000",
    "http://10.0.0.2:8080",
    "http://10.0.0.2:5173",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://10.42.0.11",
    "http://10.42.0.11:3000",
    "http://10.42.0.11:8080",
    "http://10.42.0.11:5173",
]
CORS_ALLOW_CREDENTIALS = True

# Session cookie: httpOnly (not readable by JS), long expiry
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_SAVE_EVERY_REQUEST = True


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # or 'redis://redis:6379/1' if using docker-compose service
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



# Use database sessions (no Redis required). Run: python manage.py migrate
SESSION_ENGINE = "django.contrib.sessions.backends.db"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
