FROM arch2025/ros2-base

WORKDIR /app

# --- install Python tooling -------------------------------------------------
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip python3-dev python3-venv && \
    ln -s /usr/bin/python3 /usr/local/bin/python && \
    rm -rf /var/lib/apt/lists/*

# --- install deps & copy code ----------------------------------------------
COPY requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080
