FROM ros:humble-ros-base

WORKDIR /ros2_ws
COPY ./src ./src

# build & install
RUN . /opt/ros/humble/setup.sh && \
    apt-get update && \
    apt-get install -y python3-colcon-common-extensions && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -y && \
    colcon build --symlink-install && \
    echo "source /ros2_ws/install/setup.bash" >> /etc/profile
