name: Django CI (Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.2-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build ros2_base image
      run: |
        docker build -t arch2025/ros2-base -f basestationproject/ros2_ws/Dockerfile.ros2_base basestationproject/ros2_ws
    - name: Build Django image
      run: |
        docker build -t arch2025/django-ros2 -f basestationproject/Dockerfile.django basestationproject
    - name: Run tests in container
      run: |
        docker run --network host --rm -v ${{ github.workspace }}/basestationproject:/app \
          arch2025/django-ros2 \
          bash -c "source /ros2_ws/install/setup.bash && python manage.py test"