name: React Vite CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        working-directory: basestationproject/frontend

      - name: Build project
        run: npm run build
        working-directory: basestationproject/frontend

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: basestationproject/frontend

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: basestationproject/frontend/dist
